function my_plot1(time,D,Velocity,Acceleration,P_ee)

figure(2)
plot(time(1,:),D(1,:),time(1,:),Velocity(1,:),time(1,:),Acceleration(1,:))
title('Prismatic Displacement, Velocity, and Acceleration')
legend('Displacement Joint 1 ', 'Velocity Joint 1 ', 'Acceleration Joint 1 )')
xlabel ('Time (s)')
ylabel ('Disp.    Vel.     Acc. ')

figure(3)
plot(time(2,:),D(2,:),time(2,:),Velocity(2,:),time(2,:),Acceleration(2,:))
title('Theta 2 Displacement, Velocity, and Acceleration')
legend('Displacement Joint 2 ', 'Velocity Joint 2 ', 'Acceleration Joint 2 ')
xlabel ('Time (s)')
ylabel ('Disp.     Vel.     Acc. ')

figure (4)
plot(time(3,:),D(3,:),time(3,:),Velocity(3,:),time(3,:),Acceleration(3,:))
title('Theta 3 Displacement, Velocity, and Acceleration')
legend('Displacement Joint 3 ', 'Velocity Joint 3 ', 'Acceleration Joint 3 ')
xlabel ('Time (s)')
ylabel ('Disp.     Vel.     Acc. ')

figure (5)
plot(time(4,:),D(4,:),time(4,:),Velocity(4,:),time(4,:),Acceleration(4,:))
title('Theta 4 Displacement, Velocity, and Acceleration')
legend('Displacement Joint 4 ', 'Velocity Joint 4 ', 'Acceleration Joint 4 ')
xlabel ('Time (s)')
ylabel ('Disp   Vel.     Acc. ')

figure (6)
plot(time(5,:),D(5,:),time(5,:),Velocity(5,:),time(5,:),Acceleration(5,:))
title('Theta 5 Displacement, Velocity, and Acceleration')
legend('Displacement Joint 5 ', 'Velocity Joint 5 ', 'Acceleration Joint 5 ')
xlabel ('Time (s)')
ylabel ('Disp.    Vel.     Acc. ')

figure (7)
plot(time(6,:),D(6,:),time(6,:),Velocity(6,:),time(6,:),Acceleration(6,:))
title('Theta 6 Displacement, Velocity, and Acceleration')
legend('Displacement Joint 6 ', 'Velocity Joint 6 ', 'Acceleration Joint 6 ')
xlabel ('Time (s)')
ylabel ('Disp.    Vel.     Acc. ')

figure (8)
for i=1:length(P_ee(1,:))
    px(i) = P_ee(1,i);
    py(i) = P_ee(2,i);
    pz(i) = P_ee(3,i);
end
comet3(px, py, pz)
title('Path Generation')
xlabel ('Position x')
ylabel ('Position y')
zlabel ('Position z')

figure (9)
for i = 1:length(time)
    plot(time, D(1,:))
    hold on
end
title('End Effector Displacement vs Time')

figure (10)
for i = 1:length(time)
    plot(time, Velocity(1,:))
    hold on
end
title('End Effector Velocity vs Time')

figure (11)
for i = 1:length(time)
    plot(time, Acceleration(1,:))
    hold on
end
title('End Effector Acceleration vs Time')

figure (12)
subplot(3,2,1)
plot(time(1,:),D(1,:),'-k')
title('Joint Displacements')
legend('Joint 1 ')
xlabel ('Time (s)')
ylabel ('Linear Displacement')

subplot(3,2,2)
plot(time(2,:),D(2,:),'-m')
title('Joint Displacements')
legend('Joint 2 ')
xlabel ('Time (s)')
ylabel ('Angular Displacement')

subplot(3,2,3)
plot(time(3,:),D(3,:),'-c')
title('Joint Displacements')
legend('Joint 3 ')
xlabel ('Time (s)')
ylabel ('Angular Displacement')

subplot(3,2,4)
plot(time(4,:),D(4,:),'-r')
title('Joint Displacements')
legend('Joint 4 ')
xlabel ('Time (s)')
ylabel ('Angular Displacement')

subplot(3,2,5)
plot(time(5,:),D(5,:),'-g')
title('Joint Displacements')
legend('Joint 5 ')
xlabel ('Time (s)')
ylabel ('Angular Displacement')

subplot(3,2,6)
plot(time(6,:),D(6,:),'-b')
title('Joint Displacements')
legend('Joint 6 ')
xlabel ('Time (s)')
ylabel ('Angular Displacement')


figure (13)
subplot(3,2,1)
plot(time(1,:),Velocity(1,:),'-k')
title('Joint Velocity')
legend('Joint 1 ')
xlabel ('Time (s)')
ylabel ('Linear Velocity')

subplot(3,2,2)
plot(time(2,:),Velocity(2,:),'-m')
title('Joint Velocity')
legend('Joint 2 ')
xlabel ('Time (s)')
ylabel ('Angular Velocity')

subplot(3,2,3)
plot(time(3,:),Velocity(3,:),'-c')
title('Joint Velocity')
legend('Joint 3 ')
xlabel ('Time (s)')
ylabel ('Angular Velocity')

subplot(3,2,4)
plot(time(4,:),Velocity(4,:),'-r')
title('Joint Velocity')
legend('Joint 4 ')
xlabel ('Time (s)')
ylabel ('Angular Velocity')

subplot(3,2,5)
plot(time(5,:),Velocity(5,:),'-g')
title('Joint Velocity')
legend('Joint 5 ')
xlabel ('Time (s)')
ylabel ('Angular Velocity')

subplot(3,2,6)
plot(time(6,:),Velocity(6,:),'-b')
title('Joint Velocity')
legend('Joint 6 ')
xlabel ('Time (s)')
ylabel ('Angular Velocity')

figure (14)
subplot(3,2,1)
plot(time(1,:),Acceleration(1,:),'-k')
title('Joint Acceleration')
legend('Joint 1 ')
xlabel ('Time (s)')
ylabel ('Linear Acceleration')

subplot(3,2,2)
plot(time(2,:),Acceleration(2,:),'-m')
title('Joint Acceleration')
legend('Joint 2 ')
xlabel ('Time (s)')
ylabel ('Angular Acceleration')

subplot(3,2,3)
plot(time(3,:),Acceleration(3,:),'-c')
title('Joint Acceleration')
legend('Joint 3 ')
xlabel ('Time (s)')
ylabel ('Angular Acceleration')

subplot(3,2,4)
plot(time(4,:),Acceleration(4,:),'-r')
title('Joint Acceleration')
legend('Joint 4 ')
xlabel ('Time (s)')
ylabel ('Angular Acceleration')

subplot(3,2,5)
plot(time(5,:),Acceleration(5,:),'-g')
title('Joint Acceleration')
legend('Joint 5 ')
xlabel ('Time (s)')
ylabel ('Angular Acceleration')

subplot(3,2,6)
plot(time(6,:),Acceleration(6,:),'-b')
title('Joint Acceleration')
legend('Joint 6 ')
xlabel ('Time (s)')
ylabel ('Angular Acceleration')
