function my_plot3(time,mat_ang_v,mat_ang_a,mat_lin_a,mat_lin_a_COM,mat_F_inertial,mat_N_inertial,mat_link_f,mat_link_n,mat_tau)

figure(17)
subplot(3,1,1)
plot(time(1,:),mat_ang_v(1,:),'-k')
title('Angular Velocity 1')
xlabel ('time (s)')
ylabel ('Angular Velocity 1')

subplot(3,1,2)
plot(time(1,:),mat_ang_v(2,:),'-m')
title('Angular Velocity 2')
xlabel ('time (s)')
ylabel ('Angular Velocity 2')

subplot(3,1,3)
plot(time(1,:),mat_ang_v(3,:),'-c')
title('Angular Velocity 3')
xlabel ('time (s)')
ylabel ('Angular Velocity 3')

figure(18)
subplot(3,1,1)
plot(time(1,:),mat_ang_a(1,:),'-k')
title('Angular Acceleration 1')
xlabel ('time (s)')
ylabel ('Angular Acceleration 1')

subplot(3,1,2)
plot(time(1,:),mat_ang_a(2,:),'-m')
title('Angular Acceleration 2')
xlabel ('time (s)')
ylabel ('Angular Acceleration 2')

subplot(3,1,3)
plot(time(1,:),mat_ang_a(3,:),'-c')
title('Angular Acceleration 3')
xlabel ('time (s)')
ylabel ('Angular Acceleration 3')

figure(19)
subplot(3,1,1)
plot(time(1,:),mat_lin_a(1,:),'-k')
title('Linear Acceleration 1')
xlabel ('time (s)')
ylabel ('Linear Acceleration 1')

subplot(3,1,2)
plot(time(1,:),mat_lin_a(2,:),'-m')
title('Linear Acceleration 2')
xlabel ('time (s)')
ylabel ('Linear Acceleration 2')

subplot(3,1,3)
plot(time(1,:),mat_lin_a(3,:),'-c')
title('Angular Velocity 3')
xlabel ('time (s)')
ylabel ('Linear Acceleration 3')

figure(20)
subplot(3,1,1)
plot(time(1,:),mat_lin_a_COM(1,:),'-k')
title('Linear Acceleration COM 1')
xlabel ('time (s)')
ylabel ('Linear Acceleration COM 1')

subplot(3,1,2)
plot(time(1,:),mat_lin_a_COM(2,:),'-m')
title('Linear Acceleration COM 2')
xlabel ('time (s)')
ylabel ('Linear Acceleration COM 2')

subplot(3,1,3)
plot(time(1,:),mat_lin_a_COM(3,:),'-c')
title('Linear Acceleration COM 3')
xlabel ('time (s)')
ylabel ('Linear Acceleration COM 3')

figure(21)
subplot(3,1,1)
plot(time(1,:),mat_F_inertial(1,:),'-k')
title('Inertial Force 1')
xlabel ('time (s)')
ylabel ('Inertial Force 1')

subplot(3,1,2)
plot(time(1,:),mat_F_inertial(2,:),'-m')
title('Inertial Force 2')
xlabel ('time (s)')
ylabel ('Inertial Force 2')

subplot(3,1,3)
plot(time(1,:),mat_F_inertial(3,:),'-c')
title('Inertial Force 3')
xlabel ('time (s)')
ylabel ('Inertial Force 3')

figure(22)
subplot(3,1,1)
plot(time(1,:),mat_N_inertial(1,:),'-k')
title('Inertial Moment 1')
xlabel ('time (s)')
ylabel ('Inertial Moment 1')

subplot(3,1,2)
plot(time(1,:),mat_N_inertial(2,:),'-m')
title('Inertial Moment 2')
xlabel ('time (s)')
ylabel ('Inertial Moment 2')

subplot(3,1,3)
plot(time(1,:),mat_N_inertial(3,:),'-c')
title('Inertial Moment 3')
xlabel ('time (s)')
ylabel ('Inertial Moment 1')

figure(23)
subplot(3,1,1)
plot(time(1,:),mat_link_f(1,:),'-k')
title('Link Force 1')
xlabel ('time (s)')
ylabel ('Link Force 1')

subplot(3,1,2)
plot(time(1,:),mat_link_f(2,:),'-m')
title('Link Force 2')
xlabel ('time (s)')
ylabel ('Link Force 2')

subplot(3,1,3)
plot(time(1,:),mat_link_f(3,:),'-c')
title('Link Force 3')
xlabel ('time (s)')
ylabel ('Link Force 3')

figure(24)
subplot(3,1,1)
plot(time(1,:),mat_link_n(1,:),'-k')
title('Link Moment 1')
xlabel ('time (s)')
ylabel ('Link Moment 1')

subplot(3,1,2)
plot(time(1,:),mat_link_n(2,:),'-m')
title('Link Moment 2')
xlabel ('time (s)')
ylabel ('Link Moment 2')

subplot(3,1,3)
plot(time(1,:),mat_link_n(3,:),'-c')
title('Link Moment 3')
xlabel ('time (s)')
ylabel ('Link Moment 3')

figure(25)
plot(time(1,:),mat_tau(1,:),'-r')
title('Torque')
xlabel ('time (s)')
ylabel ('Torque')